### ISSUE TITLE
EllipsizingTextView does not respect links

### ISSUE THREAD

**Issue by denisk20** [triposo/barone#6]
When setting

    ellipsizingTextView.setMovementMethod(LinkMovementMethod.getInstance());

the links in the text do not become active, while with regular TextView they do.

**Comment by tomrenn** [comment]
I've noticed in some cases the CharSequence may be immutable, being an `instanceof Spanned` instead of `Spannable`. Sometime in the next week I might add a commit to this PR that makes the comparison generalized. 

`Spannable` [implements](http://developer.android.com/reference/android/text/Spanned.html) `Spanned` catching this extra case.
